### PR TITLE
temporary stuff to fix folder creation failure on windows? maybe

### PR DESCRIPTION
**Pull request by fluffyloopy**
not pretty/good but it works?ig

### CODE REVIEW

**Comment by PreciousWarrior** [comment]
Seems good but I can see an issue with this in OSX/Linux/Unix based OS's where `/` is used for the file separator. So replacing that will save the file in the root directory which is obviously not a good idea

maybe get the OS type and replace only if the type is windows?

**Comment by fluffyloopy** [comment]
done. i have no idea what the unusable characters for nix operating systems are so, im leaving that alone

**Comment by PreciousWarrior** [comment]
The diffs are not showing properly, I have no idea what changes you made. Can you try pulling the git repo and making the changes instead of uploading the files directly? 

Also for nix based OS's the only unusable character is `/`, so if the OS is nix flavoured replace all the slashes with dash, and if the OS is windows flavoured replace all the other forbidden characters with dash. This SO answer is more detailed: https://stackoverflow.com/a/31976060. You could go ahead and remove all the ascii control characters as well though I do not expect discord to allow them as guild/emoji names

**Comment by fluffyloopy** [comment]
deleted fork and redid it. did i goof it up? the changes are just on line 3,4 and 42 to 45.

**Comment by PreciousWarrior** [comment]
LGTM, it doesnt replace `/` with `-` for unix based OS but since that wasnt there earlier im merging this PR.

still needed:
- replacing `/` with `-` for nix based OS's
- this only works for the guild name, but the emoji/sticker name might have special characters as well

**Pull request merged**
